--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Henry12960/Hardcore
build-by-default: true
branches:
- main
projects:
  Hardcore:
    path: ""
    icon: "Hardcore.png"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
      - src: CortexPE/Commando/Commando
        version:  ^3.0.0
        branch: PM4
      - src: David-pm-pl/libEco/libEco
        version: ^3.0.0
        branch: stable
...
