name: Hardcore
main: HenryDM\Hardcore\Main
api: [4.0.0]
version: 1.0.0
author: [HenryDM]
description: An advanced plugin to create a custom hardcore mode on your pocketmine server!
website: https://github.com/Henry12960

softdepend: [EconomyAPI, BedrockEconomy]


commands: 
  hardcore: 
    description: "join in hardcore gamemode"
    permision: hardcore.use
    
permissions:
  hardcore.use:
    default: true
    description: "Permission to join in hardcore mode"    
