---
# =========================
#      GENERAL CONFIG
# =========================

hardcore-worlds: ["Hardcore"]

# =========================
#     GAME OVER CONFIG
# =========================

game-over-form-title: "Test"
game-over-form-content: "Test"
game-over-form-exit-button: "Test"
...